spring:
  datasource:
    url: jdbc:mysql://localhost:3306/girls
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat

  jdbc:
    template:
      query-timeout: 3
  redis:
    client-type: jedis
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mybatis/mapper/*.xml


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true

info:
  appName: boot-admin